# src/presentation/components/attendance/overview.py

"""
Attendance Overview Component

Purpose
-------
Renders the attendance overview section for the Attendance Analytics
workspace.

Responsibilities
----------------
- Display attendance KPI cards.
- Delegate metric formatting to presentation utilities.
- Render presentation components only.

Architectural Rules
-------------------
- Presentation only.
- No business logic.
- No analytics calculations.
"""

from __future__ import annotations

# ============================================================================
# Standard Library Imports
# ============================================================================
from typing import Any

# ============================================================================
# Local Imports
# ============================================================================
from src.presentation.components.common import metric_cards
from src.presentation.utils import formatters

# ============================================================================
# Attendance Overview
# ============================================================================


def render(
    attendance: dict[str, Any],
) -> None:
    """
    Render the attendance overview section.

    Parameters
    ----------
    attendance:
        Attendance summary generated by the application layer.
    """

    metric_cards.render_section_header(
        "Attendance Overview",
        "Attendance statistics for the current session.",
    )

    metric_cards.render_metric_row(
        formatters.attendance_metrics(
            attendance,
        ),
    )
