# src/domain/models/insight_event.py

"""
Insight Event Domain Model

Purpose
-------
Represents a meaningful analytical observation derived from
domain data.

Responsibilities
----------------
- Represent an analytical insight.
- Preserve insight classification.
- Preserve insight importance.
- Provide domain-level insight behaviour.
- Remain independent of AI, pandas and UI technologies.

Domain Rules
------------
- An insight is an observation derived from domain data.
- An insight is not an AI response.
- An insight may be generated by deterministic analytics,
  an application service, or an AI-assisted process.
- The domain model does not know how the insight was generated.
- The domain model stores the resulting insight.

Notes
-----
- Immutable.
- Technology independent.
- Contains no UI, pandas, Streamlit or provider dependencies.

Author
------
OYBS Attendance Dashboard

Created
-------
July 2026
"""

from __future__ import annotations

# ============================================================================
# Standard Library Imports
# ============================================================================
from dataclasses import dataclass
from datetime import date, datetime
from enum import Enum

# ============================================================================
# Insight Classification
# ============================================================================


class InsightSeverity(str, Enum):
    """
    Classification of insight importance.
    """

    INFO = "info"

    POSITIVE = "positive"

    WARNING = "warning"

    CRITICAL = "critical"


# ============================================================================
# Insight Event
# ============================================================================


@dataclass(frozen=True, slots=True)
class InsightEvent:
    """
    Immutable analytical insight.

    Attributes
    ----------
    title:
        Short title of the insight.

    description:
        Human-readable explanation of the insight.

    severity:
        Importance classification.

    metric:
        Optional metric associated with the insight.

    value:
        Optional observed value.

    threshold:
        Optional comparison threshold.

    session_date:
        Optional date associated with the insight.

    generated_at:
        Time the insight was created.
    """

    title: str

    description: str

    severity: InsightSeverity = InsightSeverity.INFO

    metric: str | None = None

    value: float | int | str | None = None

    threshold: float | int | str | None = None

    session_date: date | None = None

    generated_at: datetime | None = None

    def __post_init__(self) -> None:
        """
        Validate and normalize the insight.
        """

        title = self.title.strip()

        if not title:
            raise ValueError(
                "title cannot be empty.",
            )

        description = self.description.strip()

        if not description:
            raise ValueError(
                "description cannot be empty.",
            )

        if not isinstance(
            self.severity,
            InsightSeverity,
        ):
            raise TypeError(
                "severity must be an InsightSeverity.",
            )

        if self.metric is not None:
            normalized_metric: str | None = self.metric.strip()

            if not normalized_metric:
                normalized_metric = None

            object.__setattr__(
                self,
                "metric",
                normalized_metric,
            )

        if self.generated_at is not None and not isinstance(
            self.generated_at,
            datetime,
        ):
            raise TypeError(
                "generated_at must be a datetime or None.",
            )

        if self.session_date is not None and not isinstance(
            self.session_date,
            date,
        ):
            raise TypeError(
                "session_date must be a date or None.",
            )

        object.__setattr__(
            self,
            "title",
            title,
        )

        object.__setattr__(
            self,
            "description",
            description,
        )

    # =========================================================================
    # Classification
    # =========================================================================

    @property
    def is_positive(self) -> bool:
        """
        Return True if the insight is positive.
        """

        return self.severity is InsightSeverity.POSITIVE

    @property
    def is_warning(self) -> bool:
        """
        Return True if the insight is a warning.
        """

        return self.severity is InsightSeverity.WARNING

    @property
    def is_critical(self) -> bool:
        """
        Return True if the insight is critical.
        """

        return self.severity is InsightSeverity.CRITICAL

    @property
    def is_informational(self) -> bool:
        """
        Return True if the insight is informational.
        """

        return self.severity is InsightSeverity.INFO

    # =========================================================================
    # Metric Information
    # =========================================================================

    @property
    def has_metric(self) -> bool:
        """
        Return True if the insight is associated with a metric.
        """

        return self.metric is not None

    @property
    def has_value(self) -> bool:
        """
        Return True if the insight has an observed value.
        """

        return self.value is not None

    @property
    def has_threshold(self) -> bool:
        """
        Return True if the insight has a threshold.
        """

        return self.threshold is not None

    # =========================================================================
    # Context
    # =========================================================================

    @property
    def is_session_specific(self) -> bool:
        """
        Return True if the insight is associated with a session date.
        """

        return self.session_date is not None

    # =========================================================================
    # Serialization
    # =========================================================================

    def to_dict(self) -> dict[str, object]:
        """
        Return dictionary representation.
        """

        return {
            "title": self.title,
            "description": self.description,
            "severity": self.severity.value,
            "metric": self.metric,
            "value": self.value,
            "threshold": self.threshold,
            "session_date": self.session_date,
            "generated_at": self.generated_at,
        }

    # =========================================================================
    # Dunder Methods
    # =========================================================================

    def __str__(self) -> str:
        """
        Return readable representation.
        """

        return f"InsightEvent(title='{self.title}', severity='{self.severity.value}')"
